content:
  - name: business-logs
    label: Business Logs
    type: collection
    path: business-logs/
    format: frontmatter-md
    view:
      label: title
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: body
        label: Content
        type: text